# Generated by Django 3.2.9 on 2021-11-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipments', '0002_alter_shipment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
